name: Actions
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm install
            - name: build project
              run: npm run build:prod
            # - name: unit test
            #   run: npm run unit:check
            # - name: e2e test
            #   run: npm run e2e:check
            - name: lint code
              run: npm run lint:check
            - name: type code
              run: npm run type:check
